name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses : actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name : Package jar
        run : ./mvnw package

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v4

      - name : Login To Docker Hub
        uses: docker/login-action@v4
        with:
          username : ${{secrets.DOCKER_USERNAME}}
          password : ${{secrets.DOCKERHUB_TOKEN}}

      - name : Build and Push Image
        uses: docker/build-push-action@v4
        with:
          push: 'true'
          tags: ${{secrets.DOCKER_USERNAME}}/react-with-spring-boot



