name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses : actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name : Package jar
        run : ./mvnw clean package

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name : Login To Docker Hub
        uses: docker/login-action@v3
        with:
          username : ${{secrets.DOCKER_USERNAME}}
          password : ${{secrets.DOCKERHUB_TOKEN}}
      - name: List files
        run: "cp target/react-with-spring-boot-0.0.1-SNAPSHOT.jar . && mv react-with-spring-boot-0.0.1-SNAPSHOT.jar app.jar && ls"
      - name : Build and Push Image
        uses: docker/build-push-action@v6
        with:
          push: 'true'
          tags: ${{secrets.DOCKER_USERNAME}}/react-with-spring-boot

      - name: List files again
        run: "ls"

